version: "3.1"

services:
  mosquitto:
    image: mosquitto
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - default
